FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    libpng-dev libjpeg-dev libfreetype6-dev libzip-dev \
    && docker-php-ext-install pdo_mysql zip bcmath gd

WORKDIR /var/www/html

# Copy from builder stage
COPY --from=builder /var/www/html /var/www/html
